"""empty message

Revision ID: 1caca5847b34
Revises: 
Create Date: 2023-01-30 15:13:08.305598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1caca5847b34'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_info',
    sa.Column('contact_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('contact_id')
    )
    op.create_table('event_info',
    sa.Column('event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_name', sa.String(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('event_time_start', sa.DateTime(), nullable=True),
    sa.Column('event_time_end', sa.DateTime(), nullable=True),
    sa.Column('event_link', sa.String(), nullable=True),
    sa.Column('event_latitude', sa.Integer(), nullable=True),
    sa.Column('event_longitude', sa.Integer(), nullable=True),
    sa.Column('event_for_family', sa.Boolean(), nullable=True),
    sa.Column('event_for_adults', sa.Boolean(), nullable=True),
    sa.Column('event_a_concert', sa.Boolean(), nullable=True),
    sa.Column('event_free', sa.Boolean(), nullable=True),
    sa.Column('event_low_cost', sa.Boolean(), nullable=True),
    sa.Column('event_address', sa.String(), nullable=True),
    sa.Column('event_city', sa.String(), nullable=True),
    sa.Column('event_zipcode', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_info')
    op.drop_table('contact_info')
    # ### end Alembic commands ###
