"""recreating migrations folder

Revision ID: 3bb11782d5d9
Revises: 
Create Date: 2023-01-25 10:17:04.349390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bb11782d5d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_info',
    sa.Column('contact_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('contact_id')
    )
    op.create_table('event_info',
    sa.Column('event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_info')
    op.drop_table('contact_info')
    # ### end Alembic commands ###
