"""empty message

Revision ID: 5fdf9ec457f0
Revises: ad79fc589988
Create Date: 2023-01-30 14:32:46.884042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fdf9ec457f0'
down_revision = 'ad79fc589988'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_info', sa.Column('event_for_family', sa.Boolean(), nullable=True))
    op.drop_column('event_info', 'event_for_famliy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_info', sa.Column('event_for_famliy', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('event_info', 'event_for_family')
    # ### end Alembic commands ###
