"""empty message

Revision ID: 60d83e876445
Revises: c3a96108f886
Create Date: 2023-02-01 13:08:15.468207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60d83e876445'
down_revision = 'c3a96108f886'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event_info', 'event_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event_info', 'event_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
