"""adds contact and event model

Revision ID: 836aa6d054b9
Revises: 
Create Date: 2023-01-24 16:08:04.461265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '836aa6d054b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_info',
    sa.Column('contact_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('contact_id')
    )
    op.create_table('event_info',
    sa.Column('event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_info')
    op.drop_table('contact_info')
    # ### end Alembic commands ###
