"""empty message

Revision ID: 8a65187e9cf9
Revises: 3bb11782d5d9
Create Date: 2023-01-26 16:11:35.038608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a65187e9cf9'
down_revision = '3bb11782d5d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_info', sa.Column('email', sa.String(), nullable=True))
    op.add_column('contact_info', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('contact_info', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact_info', 'name')
    op.drop_column('contact_info', 'last_name')
    op.drop_column('contact_info', 'email')
    # ### end Alembic commands ###
