"""empty message

Revision ID: 94c353a0f2d7
Revises: 3bb11782d5d9
Create Date: 2023-01-30 13:49:25.620260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94c353a0f2d7'
down_revision = '3bb11782d5d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_info', sa.Column('event_a_concert', sa.Boolean(), nullable=True))
    op.add_column('event_info', sa.Column('event_address', sa.Integer(), nullable=True))
    op.add_column('event_info', sa.Column('event_city', sa.Integer(), nullable=True))
    op.add_column('event_info', sa.Column('event_date', sa.Date(), nullable=True))
    op.add_column('event_info', sa.Column('event_for_adults', sa.Boolean(), nullable=True))
    op.add_column('event_info', sa.Column('event_for_famliy', sa.Boolean(), nullable=True))
    op.add_column('event_info', sa.Column('event_free', sa.Boolean(), nullable=True))
    op.add_column('event_info', sa.Column('event_latitude', sa.Integer(), nullable=True))
    op.add_column('event_info', sa.Column('event_link', sa.String(), nullable=True))
    op.add_column('event_info', sa.Column('event_longitude', sa.Integer(), nullable=True))
    op.add_column('event_info', sa.Column('event_low_cost', sa.Boolean(), nullable=True))
    op.add_column('event_info', sa.Column('event_time_end', sa.DateTime(), nullable=True))
    op.add_column('event_info', sa.Column('event_time_start', sa.DateTime(), nullable=True))
    op.add_column('event_info', sa.Column('event_zipcode', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_info', 'event_zipcode')
    op.drop_column('event_info', 'event_time_start')
    op.drop_column('event_info', 'event_time_end')
    op.drop_column('event_info', 'event_low_cost')
    op.drop_column('event_info', 'event_longitude')
    op.drop_column('event_info', 'event_link')
    op.drop_column('event_info', 'event_latitude')
    op.drop_column('event_info', 'event_free')
    op.drop_column('event_info', 'event_for_famliy')
    op.drop_column('event_info', 'event_for_adults')
    op.drop_column('event_info', 'event_date')
    op.drop_column('event_info', 'event_city')
    op.drop_column('event_info', 'event_address')
    op.drop_column('event_info', 'event_a_concert')
    # ### end Alembic commands ###
