"""empty message

Revision ID: ad79fc589988
Revises: 94c353a0f2d7
Create Date: 2023-01-30 14:03:07.993827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad79fc589988'
down_revision = '94c353a0f2d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_info', sa.Column('event_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_info', 'event_name')
    # ### end Alembic commands ###
